keys:
  # This placeholder is replaced automatically by install.sh
  - &harumi age1xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

creation_rules:
  - path_regex: Nixos/secrets\.yaml$
    key_groups:
      - age:
          - *harumi
