# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9a372b6b-0200-40c5-984d-3fe1efa690a7";
      fsType = "btrfs";
      options = [ "subvol=@" "compress=zstd:1" "ssd" "noatime" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/9a372b6b-0200-40c5-984d-3fe1efa690a7";
      fsType = "btrfs";
      options = [ "subvol=@home" "compress=zstd:3" "ssd" "noatime" "discard=async" "space_cache=v2" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/DFB3-6B77";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-uuid/b670b06e-3500-4741-a475-923be6fcd0e8";
      fsType = "btrfs";
      options = [ "compress=zstd:3" "ssd" "noatime" "discard=async" "space_cache=v2" ];
    };

  swapDevices = [ { device = "/swapfile"; } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
